version: '3.4'

services:
  redis-db:
    container_name: redis-db
    image: mdillon/postgis:11-alpine
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    restart: always